name: Create S3 Bucket

on:
  workflow_dispatch:
    inputs:
      port_context:
        description: 'Port.io context input'
        required: true

jobs:
  create-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create S3 bucket
        run: |
          BUCKET_NAME="my-unique-bucket-${GITHUB_RUN_ID}"
          REGION="${{ secrets.AWS_REGION }}"
          echo "Creating bucket: $BUCKET_NAME in region: $REGION"
          aws s3api create-bucket \
            --bucket $BUCKET_NAME \
            --region $REGION \
            --create-bucket-configuration LocationConstraint=$REGION